### ISSUE TITLE
Translate French strings to English

### ISSUE THREAD

**Issue by aklapper** [wikimedia-france/Lingua-Libre#73] opened 2018-01-05 17:57 UTC
```
$:ac\> grep -r "createTextNode(\""
web/js/widgets/studioWidget.js:	var tr = this.createRow(document.createTextNode("Locuteur"), this.speakersNode);
web/js/widgets/studioWidget.js:	table.appendChild(this.createRow(document.createTextNode("Langue"), this.langsNode));
web/js/widgets/multiRecorderWidget.js:	li.appendChild(document.createTextNode("Enregistrement manuel"));
web/js/widgets/multiRecorderWidget.js:	li.appendChild(document.createTextNode("Enregistrement par listing"));
web/js/swac-recorder/soundWidget.js:	this.nodePlay.appendChild(document.createTextNode("Écouter"));
web/js/swac-recorder/soundWidget.js:	this.nodeSend.appendChild(document.createTextNode("Enregistrer"));
web/js/swac-recorder/soundWidget.js:	this.nodeDiscard.appendChild(document.createTextNode("Annuler"));
web/js/swac-recorder/audioAuthWidget.js:	p.appendChild(document.createTextNode("Impossible d’accèder à l’interface audio ! Peut-être n’avez-vous pas branché de microphone…"));
web/js/swac-recorder/audioAuthWidget.js:	p.appendChild(document.createTextNode("Vous devez autoriser l’accès à votre carte son…"));
```
plus the `this.listingEditor.setList()` array in `./web/js/widgets/multiRecorderWidget.js`.

**Comment by hugolpz** [comment] 2018-01-20 15:48
@kamomil , i believe you have an English version ready to be pushed to master. If so, please share it up. It would be appreciate.
Duplicate of #13

**Comment by hugolpz** [comment] 2018-02-04 10:32
@kamomil, you pushed it right. We can close.

**Closed as completed by hugolpz** 2018-02-04 10:32 UTC
